### ISSUE TITLE
fix latex expressions in the readme

### ISSUE THREAD

**Issue by threadexio** [0xJoeMama/euler-problem-9#1]
Github flavored markdown does not support using `$$` for latex expressions. In the readme many such expressions are used and, currently, are not rendered and instead displayed as their latex code.

PR #2 fixes this.

**Comment by 0xJoeMama** [comment]
![image](https://github.com/user-attachments/assets/4dfaf317-2984-4814-8c16-d2346c42577e)
Doesn't seem to be the case for me.

**Comment by threadexio** [comment]
![Screenshot_20241111-090513.png](https://github.com/user-attachments/assets/b367e0da-6580-47fe-844f-0093d37b2612)

Alright then I guess it's the mobile app that doesn't support it.

**Comment by 0xJoeMama** [comment]
Checked on my side, it also doesn't work on mobile. Either way GitHub mobile is out of date as fuck.

**Comment by threadexio** [comment]
Yeah you are right, even #2 doesn't work in the mobile app... I guess this whole ordeal has been pointless then. Closing the issue and the PR.

**Comment by 0xJoeMama** [comment]
>  I guess this whole ordeal has been pointless then.

Nothing is pointless. I might actually had missed this if no one ever said anything. At least now I can blame GitHub's shitty app 🙃
